### ISSUE TITLE
User facing signup form is accessing admin signup form

### ISSUE THREAD

**Issue by BenMorganIO** [AlchemyCMS/alchemy-devise#12]
I'm noticing that inside of Alchemy Devise that when a general user signs up, its done through the admin sign up form seen [here](https://github.com/magiclabs/alchemy-devise/blob/master/app/views/alchemy/users/new.html.erb#L11).

Are we able to abstract this away so that there is a form for the general user role and another form for the admin role?

This is an issue because on a general application, I signup is causing the notification message to read "successfully signed up admin user" and, for me, there was a redirect to the signup page (done onpurpose from my routes) where the form asked if they wanted to signup with different roles.

To get back to the point, are we able to separate or abstract the signups for each alchemy role? A member would use the member signup form, an admin would use the admin signup form, and so on... I believe this would bring an enormous amount of functionality.

**Comment by tvdeyen** [comment]
Since we moved the admin signup form into `/admin` namespace now, you can rollup your own signup process. Let me know if you run into any issues.
