### ISSUE TITLE
Incompatibility with alchemy_cms ^6

### ISSUE THREAD

**Issue by Gibbo3771** [AlchemyCMS/alchemy-devise#129]
I know Alchemy for rails 6 is unstable and under development, however I believe this module is not compatible.

I managed to successfully set everything up and create an account, however now that my session has expired I am getting the following:

```
undefined local variable or method `current_alchemy_user' for #<Alchemy::Admin::UserSessionsController:0x00000000018e70>
```

I never did run `rails g alchemy:devise:install`, that task does not exist. I assume this is what is going on. Does `rails g alchemy:install` create the default devise tables? Given that I have them.

**Comment by Gibbo3771** [comment]
Upon further investigation it's coming from `lib/alchemy/admin.locale.rb`. Again I assume this is because something is breaking the rake task, or it's missing (I can't find it) so `alchemy_cms` is never going to work.

**Comment by tvdeyen** [comment]
Please try again with latest v6.0.0 version. This is compatible with Alchemy v6.0.0

Also please run the install generator. It will do the installation for you.
