### ISSUE TITLE
Upgrade path: Using the generator messes up passwords

### ISSUE THREAD

**Issue by mamhoff** [AlchemyCMS/alchemy-devise#22]
The new generator moves the devise initializer to your host app and generate a new secret token and pepper in that new initializer. This new thing broke login on an installation I had - all the passwords already in the database couldn't be verified anymore, resulting in users not being able to log in. 

I see two paths around this: 

1. (not that elegant) move the tokens in the template all the way to the top and add a comment saying: delete these lines if you're upgrading from a previous version of alchemy-devise so your passwords keep on working
2. (more elegant) have a generator alchemy:devise:upgrade that does all the necessary stuff but does not generate new tokens, but warns the user of a possible security risk because the old initializer did not have salt and pepper

What do you think?

**Comment by tvdeyen** [comment]
I think showing a note after running the install generator should be enough to warn users about the danger if they deploy the updated `devise.rb` initializer.

**Comment by tvdeyen** [comment]
![http://po.st/321Vha](One does not simply deploy changed secret keys)

**Comment by mamhoff** [comment]
This solution still sorta encourages people to commit secrets to version control, which is a bad thing. Both Rails and Devise have been pondering this issue, and they came up with using ```config/secrets.yml``` as the only file in a Rails app that should store secrets. The devise ```config.secret_key``` currently defaults to be the same as ```Rails.config.secret_key_base``` (in Rails 4.0) or ```Rails.secrets.secret_key_base``` (Rails 4.1+). The current standard Devise initializer template uses this, and I think Alchemy should use it, too. 

This does not yet get the Pepper secret out of the Devise initializer, but we're free to add more stuff to secrets.yml. I'll submit a PR with all of this.

**Comment by tvdeyen** [comment]
Yes. This sounds right. 

Honestly, I don't know if the pepper is really needed. Regarding the comments in the devise initializer it is only useful if not bcrypt is used. So maybe we can just leave commented and the developer can choose to use it or not. Just like devise does in their generator. 

Thanks.

**Comment by mamhoff** [comment]
Closed with #23.
