### ISSUE TITLE
user with role member can open /admin/users

### ISSUE THREAD

**Issue by clst** [AlchemyCMS/alchemy-devise#28]
all other pages seem to redirect to the home page but viewing all users seems to work if the url is typed in manually. It does not look like this is intended.
Using 4.0 master.

**Comment by tvdeyen** [comment]
No, this is definitely not intended. Could you send a PR that fixes this or at least provide a failing spec/example? That would be great. 

Thanks for reporting

**Comment by clst** [comment]
The weird thing while trying to debug this: it only allows :index with a freshly restarted rails server. After doing something I have not determined yet it seems to deny and redirect fine.  
To reproduce: login with a member user. Restart rails. Open /admin/users  

If I try to open the leave screen I am denied, but refreshing index works.
```/!\ Failed to permit leave on :alchemy_admin for:
#<Alchemy::User id: 2```

This is the user I tried it with:
```ruby
#<Alchemy::User:0xccfd3dc> {
                        :id => 2,
                 :firstname => "",
                  :lastname => "",
                     :login => "test",
                     :email => "<SNIP>",
                    :gender => "",
                  :language => "de",
        :encrypted_password => "<SNIP>",
             :password_salt => "",
             :sign_in_count => 4,
           :failed_attempts => 0,
           :last_request_at => 2015-07-07 12:22:28 +0200,
        :current_sign_in_at => Tue, 07 Jul 2015 10:13:55 UTC +00:00,
           :last_sign_in_at => Tue, 07 Jul 2015 10:12:22 UTC +00:00,
        :current_sign_in_ip => "<SNIP>",
           :last_sign_in_ip => "<SNIP>",
                :created_at => Mon, 06 Jul 2015 16:07:21 UTC +00:00,
                :updated_at => Tue, 07 Jul 2015 10:13:55 UTC +00:00,
                :creator_id => 1,
                :updater_id => 1,
           :cached_tag_list => "",
      :reset_password_token => nil,
    :reset_password_sent_at => nil,
             :alchemy_roles => [
        [0] "member"
    ]
}
```

**Comment by clst** [comment]
one way to suddenly make it work correctly is touching /app/controllers/alchemy/admin/users_controller.rb
Every time I change something abilities work as they should until I restart rails. I have only tried in development so far though.

**Comment by clst** [comment]
If I use better_errors to break and execute this after a restart:
```
>> current_ability.can?(:index, Alchemy::User)
=> true
>> current_ability.can?(:destroy, Alchemy::User)
=> false
>> authorize!(:index, Alchemy::User)
=> Alchemy::User(id: integer, firstname: string, lastname: string, login: string, email: string, gender: string, language: string, encrypted_password: string, password_salt: string, sign_in_count: integer, failed_attempts: integer, last_request_at: datetime, current_sign_in_at: datetime, last_sign_in_at: datetime, current_sign_in_ip: string, last_sign_in_ip: string, created_at: datetime, updated_at: datetime, creator_id: integer, updater_id: integer, cached_tag_list: text, reset_password_token: string, reset_password_sent_at: datetime, alchemy_roles: string)
```
after touching any *.rb file in the project:
```
>> current_ability.can?(:index, Alchemy::User)
=> false
>> current_ability.can?(:destroy, Alchemy::User)
=> false
>> authorize!(:index, Alchemy::User)
!! #<CanCan::AccessDenied: You are not authorized to access this page.>
```

**Comment by clst** [comment]
This fixes the problem: 2114055b774e151bf36c006cf02cd2ddc078d886
I don't know why it happens though.

**Comment by tvdeyen** [comment]
@clst the problem is the use of `read`. This is an action alias for `index` and `show`, we have to use `show` at the member role.

I will prepare a pull request.

Thanks for pointing that out!

**Comment by tvdeyen** [comment]
Oh, and Alchemy itself defines abilities for the user class. That should be removed
