### ISSUE TITLE
Undefined method `ssl_required?` on Login

### ISSUE THREAD

**Issue by mamhoff** [AlchemyCMS/alchemy-devise#30]
On a number of machines during a workshop, we experienced `Undefined method: 'ssl_required'`. Could this be due to this commit https://github.com/AlchemyCMS/alchemy-devise/commit/6f694abb0d666e49e20a9ea8136077b301457736 ?

**Comment by tvdeyen** [comment]
Hard to say without knowing the exact environment of these machines. Does this happen on all machines or only on some of them? In which controllers does this happen? And does this happen again after restarting the app? Maybe another `spring` issue?

**Comment by robinboening** [comment]
It happend on a Mac and a Linux. It seemed to appear when accessing /admin/login. in that situation there was no existing user yet. I only saw this happening on the Linux machine though. But for some reason there was no redirect to admin/signup... Instead it was admin/login throwing this error. Hard to say what really happened.

Von unterwegs gesendet

**Comment by Salzig** [comment]
That's what happening when you forget to run ```bin/rails g alchemy:devise:install```, cause the ```config.parent_controller = "Alchemy::BaseController"``` setting in 'config/initializers/devise.rb' is missing.

**Comment by tvdeyen** [comment]
Yes, confirmed. Running `bin/rails g alchemy:devise:install` after `bundle install` fixes this.

**Comment by AnniMel** [comment]
I'm afraid the bug still exists. I have installed Alchemy exactly as instructed and received **undefined method 'ssl_required'** at http://localhost:3000. Then I created a user at http://localhost:3000/admin/signup and everything worked until I logged out. After that I received the following error messages.
http://localhost:3000: **Alchemy::Page not found "/"**
http://localhost:3000/admin/login: **undefined method `ssl_required?**
