### ISSUE TITLE
Adding more devise modules

### ISSUE THREAD

**Issue by fsmanuel** [AlchemyCMS/alchemy-devise#40]
@tvdeyen I tried to add more devise modules in an engine but it didn't worked

```ruby
# engines/engine_name/app/models/user_extension.rb

Alchemy::User.module_exec do
  Alchemy::User::DEVISE_MODULES.push(:confirmable)
end
```

Can you tell me if this is the right approach or how it should be done.

Thanks it advance

**Comment by tvdeyen** [comment]
How do you load this extension? It should work if you put this in an initializer. I don't know if you really need `module_exec`. I would try without

**Comment by fsmanuel** [comment]
@tvdeyen it didn't worked in an initializer. I'm not sure why. My guess is that the constant isn't defined when the initializer runs. My approach from above only works with a new call tho devise:

```ruby
Alchemy::User.module_exec do
  Alchemy::User::DEVISE_MODULES.push(:confirmable)
  devise *Alchemy::User::DEVISE_MODULES
end
```

Without `devise *Alchemy::User::DEVISE_MODULES` I can see the module in `DEVISE_MODULES` but devise is already initialized...

Anyways thanks for the help and the great gem!
