### ISSUE TITLE
User module shows the wrong icon

### ISSUE THREAD

**Issue by wdspkr** [AlchemyCMS/alchemy-devise#42]
After upgrading AlchemyCMS, this can be seen in the admin backend.
![alchemy cms - dashboard 2016-06-14 16-48-14](https://cloud.githubusercontent.com/assets/1218622/16047312/e4389656-324f-11e6-9d6a-280188d6b383.png)

It should be a person instead of a module.

**Comment by tvdeyen** [comment]
@wdspkr fixed with #43
