### ISSUE TITLE
Module configuration via Alchemy configuration

### ISSUE THREAD

**Issue by robinboening** [AlchemyCMS/alchemy-devise#52]
I pick up the discussion from https://github.com/AlchemyCMS/alchemy-devise/issues/51 to continue the conversation in a separate thread.

Quoting myself:

> As a feature suggestion: We could provide a alchemy/config.yml in alchemy-devise that only includes the devise modules and we read from that in the Alchemy::User class.
>
> ```
> # Alchemy::User
> DEVISE_MODULES = Alchemy::Config.get(:devise_modules)
> ```
> Alchemy CMS would need to know that there is a config.yml - not sure if that would work...

Quoting @tvdeyen 

> That is a good idea (we had this once the user model was still in the core, remember?), but to achieve that there is more involved, because Alchemy does not support to add something to the config via an plugin.
>
> We could add a app/config/alchemy/devise.yml, but then we need to duplicate all the configuration reading code from the core.
>
> A solution could be to patch the core so it loads all app/config/alchemy/*.config.yml files and merges them together. So we could then have a app/config/alchemy/devise.config.yml file and use the configuration code from the core. (We can't just load all *.yml files in the app/config/alchemy folder, because the elements.yml and page_layouts.yml files also are in this folder.)
>
> Or: Change the configuration file to app/config/alchemy.yml and then load all app/config/alchemy.*.yml files into the configuration. This would follow rails conventions, but is a bigger change for existing sites.
>
> WDYT?

**Comment by tvdeyen** [comment]
@robinboening thanks, but isn't this the wrong repo? ;)

This should be discussed on the core repo, no?

**Comment by robinboening** [comment]
True... I'll move it.
