### ISSUE TITLE
Configuration of devise modules

### ISSUE THREAD

**Issue by DennisNissen** [AlchemyCMS/alchemy-devise#91]
### Steps to reproduce

Try to configure the devise modules used in `Alchemy::User` as described in `Alchemy/devise.rb` by adding a initializer that adds devise modules to `Alchemy.devise_modules`.

```ruby
# config/initializers/alchemy.rb
Alchemy.devise_modules << :fantastic_module
```

### Expected behavior

`Alchemy::User.devise_modules` should include `:fantastic_module`

### Actual behavior

No matter what modules are added to `Alchemy.devise_modules` in the initializer, `Alchemy::User.devise_modules` will always stay the same since initializers are executed **after** framework and library stuff is loaded and `Alchemy::User` already has its configured devise modules.

### System configuration

- Alchemy Version: 4.3.1
- Rails Version: 5.2.1

I actually need to remove the `:validatable` module from `Alchemy::User` since i want to add `:secure_validatable` from `devise-security` but i cannot find a good way to configure the used devise modules.

**Comment by tvdeyen** [comment]
Have you tried to only set the modules you want instead of altering the existing collection?

```rb
# config/initializers/alchemy.rb
Alchemy.devise_modules = [
  :database_authenticatable,
  :trackable,
  :timeoutable,
  :recoverable
]
```
